version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ubuntu/deploy/scripts

  - source: build/libs/app.jar
    destination: /home/ubuntu/deploy

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60