version: 0.0
os: linux
files:
  - source: scripts/
    destination: /home/ubuntu/deploy/scripts

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
  AfterInstall:
    - location: scripts/start.sh
      timeout: 120