spring:
  web:
    cors:
      allowed-origins:
        - "https://riverendingstory.site"
        - "https://www.riverendingstory.site"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true