name: CI/CD (Jar Deploy)

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [terraform-complete]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy application.yml from submodule
        shell: bash
        run: cp Backend-properties/application-prod.yml src/main/resources/application-prod.yml

      - name: Build Spring Boot App
        run: ./gradlew clean bootJar

      - name: Zip deployment package
        run: zip -r spring-boot-deploy.zip appspec.yml scripts/ build/libs/app.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp spring-boot-deploy.zip s3://${{ secrets.S3_BUCKET }}/spring-boot-deploy.zip

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=spring-boot-deploy.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE